title: dr Olga Lewandowska

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
permalink: /:title/

include:
- _pages

plugins:
- jekyll-include-cache

author:
  name: "dr Olga Lewandowska"
  avatar: "/images/olgalewandowska_avatar.jpg"

defaults:
- scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: false
    sidebar:
      nav: "main"
