title: dr Olga Lewandowska

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

include:
- _pages

plugins:
- jekyll-include-cache

author:
  name: "dr Olga Lewandowska"
  avatar: "/images/olgalewandowska.jpg"

defaults:
- scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: true
