title: dr Olga Lewandowska

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint

plugins:
- jekyll-include-cache

defaults:
- scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: true
